# Generated by Django 4.0.5 on 2022-06-25 21:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='home.homepage')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailmedia.media')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
